EEWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', IndexView.as_view(), name = 'home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('site_auth.urls')),
    path('preelec9_camp/', include('preelec9_camp.urls')),
    path('camp/', include('preelec_online.urls'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

preelec9_camp/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView
from .views import *

urlpatterns = [
    path('', CampIndexView.as_view()),
    path('63/statement/', CampStatementView.as_view()),
    path('63/register/', RegisterView_63.as_view()),
    path('63/buyshirt/', RegisterView_6x.as_view()),
    path('63/camp_listview/', CampListView_63.as_view()),
    path('63/camp_listview/<int:pk>/', CampDetailView_63.as_view()),
    path('63/camp_register/<int:pk>/', CampRegistrarView_63.as_view()),
    path('63/unregister/', CampUnregisterView_63.as_view()),
    path('63/viewdata/',Viewdata_63.as_view()),
    path('63/abstract/',Abstract.as_view()),
    path('63/abstract/allergy/',Allergy.as_view()),
    path('63/abstract/checkregister/',CheckRegister.as_view()),
    path('63/abstract/checkshirt/',Checkshirt.as_view()),
    path('64/register/', RegisterView_64.as_view()),
    path('64/register/confirm/', CampConfirmView.as_view()),
    path('64/unregister/', CampUnregisterView.as_view()),
    path('64/viewdata/', DataView_64.as_view()),
    path('64/parent/', CampParentView.as_view()),
    path('qrcode/<int:pk>/', QRView.as_view(), name='qrcode')   
]

preelec9_camp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
class Statement(models.Model):
    class Meta:
        verbose_name = "Statement"
        verbose_name_plural = "Statements"
    division_choices = [
        ('Art', 'Art'),
        ('Data', 'Data'),
        ('Delivery', 'Delivery'),
        ('Local', 'Local'),
        ('Medic', 'Medic'),
        ('PR', 'PR'),
        ('Recreation', 'Recreation'),
        ('Security', 'Security'),
        ('Secretary', 'Secretary'),
        ('Welfare', 'Welfare'),
        ('Treasurer', 'Treasurer'),
        ('Welcome Box','Welcome Box'),
        ('Other', 'Other')
    ]
    mode_choices = [
        ('รายรับ', 'รายรับ'),
        ('รายจ่าย', 'รายจ่าย'),
    ]
    division = models.CharField(max_length=100, choices=division_choices)
    mode = models.CharField(max_length=100, choices = mode_choices)
    item_name = models.CharField(max_length=300, default='')
    transaction_date = models.DateField(null=True)
    add_date = models.DateField(null=True, default= timezone.now)
    price = models.FloatField(null=True)
    quantity = models.IntegerField(null=True)
    remarks = models.CharField(max_length=1000, null= True)
    def get_data_by_division(self, division, *args, **kwargs):
        data1 = self.objects.filter(division = division, mode = 'รายรับ').values()
        data2 = self.objects.filter(division = division, mode = 'รายจ่าย').values()
        result = []; total1 = 0; total2 =0
        def add_data_to_template(*args, **kwargs):
            data_template = {
                'transaction_date' : args[0].strftime('%Y-%m-%d'),
                'name' : args[1], 'quantity' : args[2],
                'price' : args[3], 'income' : args[4],
                'expenditure' : args[5], 'remarks' : args[6]
            }
            return data_template
        def sort_key(d):
            return d['transaction_date']
        for i in range(len(data1)):
            st = data1[i]['price']*data1[i]['quantity']
            total1 = total1 + st
            result.append(add_data_to_template(
                data1[i]['transaction_date'], data1[i]['item_name'],
                data1[i]['quantity'], data1[i]['price'], st, '-', 
                data1[i]['remarks']
            ))
        for i in range(len(data2)):
            st = data2[i]['price']*data2[i]['quantity']
            total2 = total2 - st
            result.append(add_data_to_template(
                data2[i]['transaction_date'], data2[i]['item_name'],
                data2[i]['quantity'], data2[i]['price'], '-', st,
                data2[i]['remarks']
            ))
        result.sort(key = sort_key)
        return result, total1,total2
          
    def __str__(self):
        return str(self.item_name)
    
class Campdata_64(models.Model):
    class Meta:
        verbose_name = "Camp Data 64"
        verbose_name_plural = "Camp Data 64"
    shirt_size_choices = [
        ('SS', 'SS (34"/26")'),
        ('S', 'S (36"/27")'),
        ('M', 'M (38"/28")'),
        ('L', 'L (40"/29")'),
        ('XL', 'XL (42"/30")'),
        ('XXL', 'XXL (44"/31")'),
    ]
    house_choices = [
        ('AR', 'Ares'),
        ('PO', 'Poseidon'),
        ('ZE', 'Zeus'),
        ('HE', 'Hermes'),
    ]
    parent_gender_choices = [
        ('นาย', 'นาย'),
        ('นาง', 'นาง'),
        ('นางสาว', 'นางสาว'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    shirt_size = models.CharField(max_length=100, choices = shirt_size_choices)
    passion = models.CharField(max_length=1000, null= True)
    parent_telephone_num = models.CharField(max_length=10, null= True)
    parent_gender=models.CharField(max_length=10, null= True, choices=parent_gender_choices)
    parent_name = models.CharField(max_length=100, null= True)
    parent_surname = models.CharField(max_length=100, null= True)
    parent_relation = models.CharField(max_length=100, null= True)
    completed = models.BooleanField(default=False)
    #registered = models.BooleanField(default=False)
    house = models.CharField(max_length=2, choices = house_choices, null=True)
    def __str__(self):
        return str(self.user)
    def random_house(self):
        def assign_house(object, num):
            object.house = self.house_choices[num % 4][0]
            object.save()
        count1 = 0; count2=0
        for obj in self.objects.all():
            if obj.user.eeuserprofile.gender == 'นาย':
                assign_house(obj, count1)
                count1 += 1
            else: 
                assign_house(obj, count2)
                count2 += 1

        
class Camp_Registered_64(models.Model):
    class Meta:
        verbose_name = "Camp Registered 64"
        verbose_name_plural = "Camp Registered 64"
    campdata_64 = models.ForeignKey(Campdata_64, on_delete=models.CASCADE)
    registered_on_1 = models.DateTimeField(null= True)
    registered_on_2 = models.DateTimeField(null= True)
    registered_by_1 = models.ForeignKey(User, on_delete=models.CASCADE)
    registered_by_2 = models.CharField(null = True, max_length=200)
    comment = models.CharField(max_length=300, null=True)
    def __str__(self):
        return str(self.campdata_64)

class Campdata_63(models.Model):
    class Meta:
        verbose_name = "Camp Data 63"
        verbose_name_plural = "Camp Data 63"
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    check_shirt = models.ImageField('หลักฐานการโอน',upload_to='images/preelec9_camp/shirt',null=True)
    confirmed = models.BooleanField(default=False)
    def __str__(self):
        return str(self.user)

class Campdata_6x(models.Model):
    class Meta:
        verbose_name = "Camp Data 6x"
        verbose_name_plural = "Camp Data 6x"
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    check_shirt = models.ImageField('หลักฐานการโอน',upload_to='images/preelec9_camp/shirt',null=True)
    def __str__(self):
        return str(self.user)

class Shirt(models.Model):
    class Meta:
        verbose_name = "Size_shirt"
        verbose_name_plural = "Size_shirt"

    shirt_size_choices = [
        ('SS', 'SS (34"/26")'),
        ('S', 'S (36"/27")'),
        ('M', 'M (38"/28")'),
        ('L', 'L (40"/29")'),
        ('XL', 'XL (42"/30")'),
        ('XXL', 'XXL (44"/31")'),
    ]
    shirt_quantity_choices = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    ]
    shirt_color_choices = [
        ('black', 'black'),
        ('white', 'white'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    size_shirt = models.CharField(max_length=100, choices = shirt_size_choices)
    quantity_shirt = models.CharField(max_length=100, choices = shirt_quantity_choices)
    color_shirt = models.CharField(max_length=100, choices = shirt_color_choices)
    def __str__(self):
        return str(self.user)

preelec9_camp/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets,Select,Textarea
from .models import Campdata_64, Statement,Shirt,Campdata_63
class RegisterForm_64(forms.ModelForm):
    class Meta:
        model = Campdata_64
        fields = '__all__'
        exclude = ['user', 'completed', 'registered', 'house']
        widgets = {'shirt_size' : Select(attrs={'type': 'text','class': 'form-control', 'placeholder':'เลือกไซส์เสื้อ'},choices=Campdata_64.shirt_size_choices),
                    'parent_gender' : Select(attrs={'type': 'text','class': 'form-control', 'placeholder':'เลือกไซส์เสื้อ'},choices=Campdata_64.parent_gender_choices),
                    'passion' : forms.Textarea(attrs={'type': 'text','class': 'form-control', 'placeholder':'มีอะไรจะบอกพี่ๆ, ทำไมถึงเข้าที่นี่, สิ่งที่คาดหวังจากที่นี่'}),
                    'parent_telephone_num' : forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'เบอร์ติดต่อผู้ปกครอง'}),
                    'parent_name': forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'ชื่อผู้ปกครอง'}),
                    'parent_surname': forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'นามสกุลผู้ปกครอง'}),
                    'parent_relation': forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'บิดา, มารดา , .....'})
        
        }
class StatementForm_63(forms.Form):
    division_choices = [
        ('Art', 'Art'),
        ('Data', 'Data'),
        ('Delivery', 'Delivery'),
        ('Local', 'Local'),
        ('Medic', 'Medic'),
        ('PR', 'PR'),
        ('Recreation', 'Recreation'),
        ('Security', 'Security'),
        ('Secretary', 'Secretary'),
        ('Welfare', 'Welfare'),
        ('Treasurer', 'Treasurer'),
        ('Welcome Box','Welcome Box'),
        ('Other', 'Other'),
    ]
    division = forms.ChoiceField(
        choices = division_choices, label = 'เลือกฝ่าย',
        widget=Select(attrs={'type': 'text','class': 'form-control'}
        ))

class RegisterForm_63(forms.ModelForm):
    class Meta:
        model = Shirt
        fields = '__all__'
        exclude = ['user']
        widgets = {'size_shirt' : Select(attrs={'type': 'text','class': 'form-control', 'placeholder':'เลือกไซส์เสื้อ'},choices=Shirt.shirt_size_choices),
                    'quantity_shirt' : Select(attrs={'type': 'text','class': 'form-control', 'placeholder':'เลือกไซส์เสื้อ'},choices=Shirt.shirt_quantity_choices),
                    'color_shirt' : Select(attrs={'type': 'text','class': 'form-control', 'placeholder':'เลือกไซส์เสื้อ'},choices=Shirt.shirt_color_choices)
                    
    }

class Check_shirtForm(forms.ModelForm):
    class Meta:
        model = Campdata_63
        fields = ['check_shirt']
        

preelec9_camp/templates/preelec9_camp/63/confirm.html
{% extends 'base.html' %}

{%block header%}
{% include  'preelec9_camp/base_header.html' %}
<style>
  h1{
    text-align: center;
  }
  p1{
  color: rgb(255, 0, 0);
  }
  
</style>
{% endblock%}
{% block content%}
<div style="padding-top: 10%; padding-bottom: 10%; margin: 30px 10px 10px 10px">
  <div class="card bg-light" style="padding: 3%; max-width: 800px; margin: auto;" >
      <article  class="center" style="max-width: 800px; ">
<h1>ลงทะเบียนสำเร็จ</h1><br>
<p>ยินดีต้อนรับน้อง <p1>{{data.nickname}}</p1> สู่ค่าย PreElec 9 พิมพ์<a href='/camp/64/parent'>ใบขออนุญาตผู้ปกครอง</a>และนำมาส่งให้พี่ๆ ฝ่ายลงทะเบียนในวันค่าย ไว้มาเจอกันในค่ายนะน้อง <p1>{{data.nickname}}</p1> พี่ๆรอน้องอยู่</p>

<h3>ข้อตกลงและเงื่อนไขในการเข้าค่าย</h3>
<h6>&nbsp;&nbsp;&nbsp;1....</h6>
<h6>&nbsp;&nbsp;&nbsp;2....</h6><br>

<form action="" method='post'>
  {%csrf_token%}
  <input type="submit" class="btn btn-success btn-sm btn-block" value="ยอมรับเงื่อนไขและยืนยันการสมัคร" name = 'confirm'>
  <input type="submit" class="btn btn-danger btn-sm btn-block" value="ไม่ต้องการการสมัคร" name = 'delete'>
</form> 
</article>
</div>
</div>
{% endblock %}

preelec9_camp/templates/preelec9_camp/63/detailview.html
{% extends 'base.html' %}

{%block header%}
{% include  'preelec9_camp/base_header.html' %}
<style>
  h1{
    text-align: center;
  }
ul li{
  margin: 2%;
  font-size: 20px;
  }

</style>
{% endblock%}
{% block content%}
<div style="padding-top: 10%; padding-bottom: 10%; max-height: 10000px; margin: 20px 10px 10px 10px ">
  <div class="card bg-light" style="padding: 3%; max-width: 800px; margin: auto;" >
      <article  class="center" style="max-width: 800px; ">
<h1>ข้อมูลส่วนตัว</h1>
<ul>
  <h4>ข้อมูลทั่วไป</h4>
    <li>คำนำหน้า : {{user.eeuserprofile.gender}}</li>
    <li>ชื่อ-นามสกุล : {{user.eeuserprofile.name}} {{user.eeuserprofile.surname}}</li>
    <li>ชื่อเล่น : {{user.eeuserprofile.nickname}}</li>
    <li>รหัสนักศึกษา : {{user.eeuserprofile.student_id}}</li>
    <li>วันเดือนปีเกิด : {{user.eeuserprofile.birth_date}}</li>
    <li>ศาสนา : {{user.eeuserprofile.religion}}</li>
    <h4>ข้อมูลติดต่อ</h4>
    <li>ที่อยู่ : {{user.eeuserprofile.address}}</li>
    <li>หมายเลขโทรศัพท์ : {{user.eeuserprofile.self_telephone_num}}</li>
    <li>Line id : {{user.eeuserprofile.line_id}}</li>
    <li>Facebook : {{user.eeuserprofile.facebook}}</li>
    <li>instagram : {{user.eeuserprofile.instagram}}</li>
    <h4>ประวัติการแพ้</h4>
    <li>อาหารที่แพ้ : {{user.eeuserprofile.allergic_foods}}</li>
    <li>ยาที่แพ้ : {{user.eeuserprofile.allergic_meds}}</li>
    <li>โรคประจำตัว : {{user.eeuserprofile.congenital_disease}}</li>
</ul>
<h6> &nbsp; </h6>
<h1>ข้อมูลค่าย</h1>
<ul>
    <li>ไซส์เสื้อ : {{user.campdata_64.shirt_size}}</li>
    <li>สิ่งที่อยากจะบอก : {{user.campdata_64.passion}}</li>
    <li>คำนำหน้าผู้ปกครอง : {{user.campdata_64.parent_gender}}</li>
    <li>ชื่อผู้ปกครอง : {{user.campdata_64.parent_name}} {{user.campdata_64.parent_surname}} </li>
    <li>เกี่ยวข้องเป็น : {{user.campdata_64.parent_relation}}</li>
    <li>เบอร์โทรผู้ปกครอง : {{user.campdata_64.parent_telephone_num}}</li>
</ul>
</article>
</div>
</div>
{% endblock %}

preelec9_camp/templates/preelec9_camp/63/listview.html
{% extends 'base.html' %}
{% load static%}
{%block header%}
<style>
  td{
    text-align: center;
  }
  th{
    text-align: center;
  }
</style>
{% include  'preelec9_camp/base_header.html' %}
{% endblock%}
{% block content%}
<div style="padding-top: 10%; padding-bottom: 10%; max-height: 50000px ; margin: 30px 10px 10px 10px  ">
    <div class="card bg-light " style="padding: 3%; max-width: 1200px; margin: auto;" >
        <article  class="center" style="max-width: 1200px; ">

{%if data%}
<ul>
  {%for obj in data%}
    <li>obj</li>
  {%endfor%}
</ul>
{%else%}
<h2 style="text-align: center;">ข้อมูลน้อง</h2>
<p style="color:crimson">กดที่รหัสนักศึกษาเพื่อดูข้อมูลน้อง</p>
  
  <div class="table-responsive">       
  <table class="table table-hover">
    <thead>
      <tr>
        <th>รหัสนักศึกษา</th>
        <th>ชื่อ - นามสกุล</th>
        <th>ชื่อเล่น</th>
        <th>การดำเนินการ</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
      <tr> 
        <td><a href="{{obj.pk}}">{{ obj.user.eeuserprofile.student_id }}</a></td>
        <td >{{obj.user.eeuserprofile.gender}} {{obj.user.eeuserprofile.name}} {{obj.user.eeuserprofile.surname}}</td>
        <td>{{obj.user.eeuserprofile.nickname}}</td>
        <td><a class="btn btn-success" href='../camp_register/{{obj.pk}}'>ลงทะเบียน</a></td>
    
    {% empty %}
        <li>ยังไม่มีผู้ลงทะเบียนสำเร็จ</li>
    {% endfor %}
      </tr>
    
    </tbody>
  </table>
  </div>
  {%endif%}
  
</article>
</div>
</div>
{% endblock %}

preelec9_camp/templates/preelec9_camp/63/register.html
{% extends 'base.html' %}
{% load static%}
{%block header%}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<style>
    h2 {
        text-align: center;
    }

    h1 {
        text-align: center;
    }

    h3 {
        text-align: center;
    }

    tr {
        text-align: center;
    }

    td {
        text-align: center;
    }
</style>
{% include  'preelec9_camp/base_header.html' %}
{% endblock%}
{% block content%}
{% if not year%}
{% if not confirmed%}
{%if img_obj%}

<div style="padding-top: 10%; padding-bottom: 5%; max-height: 5000px ; margin: 50px 10px 10px 10px  ">
    <div class="card bg-light " style="padding: 3%; max-width: 800px; margin: auto;">
        <article class="center" style="max-width: 800px; ">
        <h2>สมัครค่าย Pre-Elec 9</h2>
        <p>สมัครเลย</p>
        <form action='' method='post'>
                {% csrf_token %}
                <input class="btn btn-success btn-sm btn-block" type='submit' name="regis" value='สมัครค่าย'>
            </form>
        </article>
    </div>
</div>
{%endif%}
{%endif%}
{%endif%}
<div style="padding-top: 5%;  margin: 10px 10px 10px 10px">
    </div>
    
<div style=" padding-bottom: 10%; max-height: 5000px ; margin: 30px 10px 10px 10px  ">
    <div class="card bg-light " style="padding: 3%; max-width: 800px; margin: auto;">
        <article class="center" style="max-width: 800px; ">
            {% if not img_obj%}
            <h1>สั่งซื้อเสื้อค่าย</h1>
            <form action='' method='post'>
                {% csrf_token %}
                <p>
                    <label for="id_shirt_size">ไซส์ : ขนาดรอบอก กว้าง/ยาว(โดยประมาณ)<p1>{{ form.shirt_size.errors }}</p1></label>
                </p>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-bag-check-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zm-.646 5.354a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z" />
                            </svg>
                        </span>
                    </div>
                    {{ form.size_shirt}}
                </div>
                <p><label for="id_shirt_size">จำนวน : <p1>{{ form.shirt_size.errors }}</p1></label> </p>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                fill="currentColor" class="bi bi-bag-check-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zm-.646 5.354a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z" />
                            </svg> </span>
                    </div>
                    {{ form.quantity_shirt}}
                </div>
                <p><label for="id_shirt_size">สี : <p1>{{ form.shirt_size.errors }}</p1></label> </p>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                fill="currentColor" class="bi bi-bag-check-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zm-.646 5.354a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z" />
                            </svg> </span>
                    </div>
                    {{ form.color_shirt}}
                </div>
                <input class="btn btn-primary btn-sm btn-block" type='submit' name="submit" value='เพิ่มรายการ'>
            </form>
            {%else%}
            <h2>รายการสั่งซื้อ</h2>
            {%endif%}
            <h5>&nbsp;</h5>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>รายการที่</th>
                        <th>ไซส์</th>
                        <th>จำนวน</th>
                        <th>สี</th>
                        <th>ราคา</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in shirt %}
                    <tr>
                        <td class="align-middle"><a>{{forloop.counter}}</a></td>
                        <td class="align-middle">{{obj.size_shirt}}</td>
                        <td class="align-middle">{{obj.quantity_shirt}}</td>
                        <td class="align-middle">{{obj.color_shirt}}</td>
                        <td class="align-middle">{% widthratio obj.quantity_shirt 1 price   %} </td>
                        <td class="align-middle">
                            {% if not img_obj%}
                            <form action='' method='post'>
                                {% csrf_token %}
                                <input type='hidden' name='regID' value='{{obj.pk}}'>
                                <button type='submit' class="btn btn-danger" name='delete' style="padding:none;">
                                    <i class="fa fa-times"></i></button>
                            </form>
                            {% endif %}
                        </td>
                        {% empty %}
                        <td>ยังไม่เพิ่มรายการ</td>
                        {% endfor %}
                    </tr>

                </tbody>
            </table>
            </div>
            <input class="btn btn-warning btn-sm btn-block" value='ราคาที่ต้องโอน {{ total }}'>
            <h2>&nbsp;</h2>
            {% if img_obj %}
            
            <h3>ได้รับข้อมูลเเล้ว ขอบคุณที่สั่งซื้อเสื้อ {{img_obj.title}}</h3>
            <h5 style="color: red;">ถ้าเกิดปัญหา หรือต้องการสั่งซื้อเสื้อเพิ่มเติม ติดต่อ Data</h5>
            <img src="{{ img_obj.url}}" alt="connect" class="mx-auto d-block" style="max-height:300px">
            {% else %}
            <h3>กสิกร</h3>
                <h3>xxx-xxxx-xxxxx</h3>
            {% endif %}
            <h2>&nbsp;</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form2.as_p}}
                <button type="submit" class="btn btn-info" name="upload">
                {% if not img_obj%}
                <i class="bi bi-upload"></i> อัพโหลดภาพและสมัครค่าย
                {%else%}
                <i class="bi bi-pencil-square"></i> บันทึกการเปลี่ยนแปลง
                {%endif%}
                </button>
            </form>
            
            {%if img_obj%}
            {% if not year %}
            {% if confirmed %}
            <h2>&nbsp;</h2>
            <h2>เราสมัครค่ายให้เเล้ว ลุยเลย</h2>
            <a href="/camp/" class="btn btn-success btn-sm btn-block" type='submit' name="regis">กลับหน้าค่าย</a>
            {%endif%}
            {%else%}
            <h2>&nbsp;</h2>
            <h2>THANK YOU</h2>
            {%endif%}
            {%else%}
            {% if not year %}
                <form action='' method='post'>
                    {% csrf_token %}
                    <h2>&nbsp;</h2>
                    <h2 style="color: crimson">ถ้าไม่ต้องการสั่งซื้อเสื้อค่าย ก็สมัครเลย!!</h2>
                    <input class="btn btn-success btn-sm btn-block" type='submit' name="regis" value='สมัครค่าย'>
                </form>
            {%else%}
            
                <h2>&nbsp;</h2>
            {%endif%}  
           
            {%endif%}

        </article>
    </div>
</div>

{% endblock %}