EEWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', IndexView.as_view(), name = 'home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('site_auth.urls')),
    path('preelec9_camp/', include('preelec9_camp.urls')),
    path('camp/', include('preelec_online.urls'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

site_auth/urls.py
from django.urls import path, include
from .views import UserProfileView, CheckProfileView
urlpatterns = [
    #path('base/',TemplateView.as_view(template_name='account/base.html')),
    path('', include('allauth.urls')),
    path('userprofile/', UserProfileView.as_view(), name='site_auth_userprofile'),
    path('profile/', CheckProfileView.as_view()),
    path('api-auth/', include('rest_framework.urls')),
]

site_auth/models.py
from django.db import models
from django.contrib.auth.models import User

class EEUserProfile(models.Model):
    gender_choices = [
        ('นาย', 'นาย'),
        ('นางสาว', 'นางสาว'),
    ]
    religion_choices = [
        ('พุทธ', 'พุทธ'),
        ('คริสต์', 'คริสต์'),
        ('อิสลาม', 'อิสลาม'),
        ('อื่นๆ', 'อื่นๆ'),
    ]
    class Meta:
        db_table = 'auth_userprofile'
        verbose_name = "EEUserProfile"
        verbose_name_plural = "EEUserProfile"
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    gender = models.CharField(choices=gender_choices, max_length=6, null=True)
    name = models.CharField(max_length=100,null=True)
    surname = models.CharField(max_length=100,null=True)
    eng_name = models.CharField(max_length=100,null=True)
    eng_surname = models.CharField(max_length=100,null=True)
    nickname = models.CharField(max_length=30,null=True)
    student_id = models.IntegerField(null=True)
    birth_date = models.DateField(null=True)
    address = models.CharField(max_length=1000, null=True)
    self_telephone_num = models.CharField(max_length=10, null=True)
    line_id = models.CharField(max_length=100, null=True)
    facebook = models.CharField(max_length=100, null=True)
    instagram = models.CharField(max_length=100, null=True)
    religion = models.CharField(choices=religion_choices, max_length=6, null=True)
    allergic_foods = models.CharField(max_length=200, null=True)
    allergic_meds = models.CharField(max_length=200, null=True)
    congenital_disease =  models.CharField(max_length=100, null=True)
    completed = models.BooleanField(default= False)
    def __str__(self):
        return '{} {}'.format(self.name , self.surname)
    def updatename():
        db = EEUserProfile.objects.all()
        for obj in db:
            obj.eng_name = str(obj.user.first_name).title()
            obj.eng_surname = str(obj.user.last_name).title()
            obj.save()
        return True

class EEData(models.Model):
    class Meta:
        abstract = True
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100,null=True)
    student_id = models.IntegerField(null=True)
    self_telephone_num = models.CharField(max_length=10, null=True)
    email = models.EmailField(max_length=200, null=True)
    email2 = models.EmailField(max_length=200, null=True)
    line_id = models.CharField(max_length=100, null=True)
    birth_date = models.DateField(null=True)
    nickname = models.CharField(max_length=30,null=True)
    used = models.BooleanField(default=False)
    def __str__(self):
        return '{} {}'.format(self.name , self.surname)

class EEData_63(EEData):
    class Meta:
        verbose_name = "EEData63"
        verbose_name_plural = "EEData63"

class EEData_64(EEData):
    class Meta:
        verbose_name = "EEData64"
        verbose_name_plural = "EEData64"

class EEData_62(EEData):
    class Meta:
        verbose_name = "EEData62"
        verbose_name_plural = "EEData62"

class EEData_61(EEData):
    class Meta:
        verbose_name = "EEData61"
        verbose_name_plural = "EEData61"

site_auth/forms.py
from allauth.account.forms import LoginForm,SignupForm,ChangePasswordForm,ResetPasswordForm,AddEmailForm
from django import forms
from django.forms import fields,DateInput,Select,Textarea, widgets

from .models import EEUserProfile

class EELoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(EELoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget = forms.TextInput(attrs={'type': 'text', 'class': 'form-control', 'placeholder':'ชื่อผู้ใช้'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'รหัสผ่าน'})

class EESignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super(EESignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={'type': 'text', 'class': 'form-control', 'placeholder':'ชื่อผู้ใช้'})
        self.fields['email'].widget = forms.TextInput(attrs={'type': 'email','class': 'form-control', 'placeholder':'อีเมล'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'type': 'password','class': 'form-control', 'placeholder':'รหัสผ่าน'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'type': 'password','class': 'form-control', 'placeholder':'ยืนยันรหัสผ่าน'})

class EEChangePasswordForm(ChangePasswordForm):
    def __init__(self, *args, **kwargs):
        super(EEChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields['oldpassword'].widget = forms.PasswordInput(attrs={'type': 'password','class': 'form-control', 'placeholder':'รหัสผ่านปัจจุบัน'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'type': 'password','class': 'form-control', 'placeholder':'รหัสผ่านใหม่'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'type': 'password','class': 'form-control', 'placeholder':'ยืนยันรหัสผ่านใหม่'})

class EEResetPasswordForm(ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(EEResetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(attrs={'type': 'email','class': 'form-control', 'placeholder':'อีเมล'})

class ProfileForm(forms.ModelForm):
    class Meta:
        model = EEUserProfile
        fields = '__all__'
        exclude = ['user', 'completed']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['gender'].widget = Select(attrs={'type': 'text','class': 'form-control', 'placeholder':'เพศ'},choices=EEUserProfile.gender_choices)
        self.fields['name'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'ชื่อ'})
        self.fields['surname'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'นามสกุล'})
        self.fields['eng_name'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'ชื่อ (ภาษาอังกฤษ)'})
        self.fields['eng_surname'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'นามสกุล (ภาษาอังกฤษ)'})
        self.fields['nickname'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'ชื่อเล่น'})
        self.fields['student_id'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'รหัสนักศึกษา'})
        self.fields['birth_date'].widget = DateInput(attrs={'type': 'date'})
        self.fields['address'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'ที่อยู่'})
        self.fields['self_telephone_num'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'เบอร์โทรศัพท์ส่วนตัว'})
        self.fields['line_id'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'Line id'})
        self.fields['facebook'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'Facebook'})
        self.fields['instagram'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'instagram '})
        self.fields['religion'].widget = Select(attrs={'type': 'text','class': 'form-control', 'placeholder':'ศาสนา'},choices=EEUserProfile.religion_choices)
        self.fields['allergic_foods'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'อาหารที่แพ้'})
        self.fields['allergic_meds'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'ยาที่แพ้ '})
        self.fields['congenital_disease'].widget = forms.TextInput(attrs={'type': 'text','class': 'form-control', 'placeholder':'โรคประจำตัว '})


class EEAddEmailForm(AddEmailForm):
    def __init__(self, *args, **kwargs):
        super(EEAddEmailForm, self).__init__(*args, **kwargs)
        
        self.fields['email'].widget = forms.TextInput(attrs={'type': 'email','class': 'form-control', 'placeholder':'อีเมล'})

site_auth/views.py
from django.db.models.query import InstanceCheckMeta
from django.http import request
from django.http.response import HttpResponseRedirect
from django.views.generic import View
from django.views.generic.edit import FormView
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import EEUserProfile
from .forms import ProfileForm

class CheckProfileView(View):
    def get(self,request,*args, **kwargs):
        try: 
            db = EEUserProfile.objects.get(user = request.user, completed = True)
            return redirect('home')
        except:
            return redirect('site_auth_userprofile')
        

class UserProfileView(FormView):
    template_name = 'profile/userprofile.html'
    form_class = ProfileForm
    success_url = '/accounts/userprofile'
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    def get_context_data(self,*args, **kwargs):
        context = super(UserProfileView, self).get_context_data(*args,**kwargs)
        data = EEUserProfile.objects.get(user = self.request.user)
        context['title_name'] = 'User Profile'
        context['data'] = data
        try:
            context['back_url'] = self.request.GET['next']
        except: context['back_url'] = '/'
        if 'edit' in self.request.GET.keys():
            context['completed'] = not bool(int(self.request.GET['edit']))
        else:
            context['completed'] = data.completed
        if 'message' in self.request.GET.keys():
            message = {
                'shop' : 'โปรดกดบันทึกข้อมูลเพื่อทำการชำระเงินต่อไป'
            }
            context['message'] = message[str(self.request.GET['message'])]
        return context
    def get(self, request, *args, **kwargs):
        try: 
            EEUserProfile.objects.filter(user = request.user).values()[0]
        except:
            db = EEUserProfile(user = request.user)
            db.save()
        self.initial = EEUserProfile.objects.filter(user = request.user).values()[0]
        return super().get(request,*args, **kwargs)
    '''
    def post(self,*args, **kwargs):
        form = ProfileForm(self.request.POST)
        print(form.is_valid())
        print(self.request.POST)
        return HttpResponseRedirect(self.request.path_info)
    '''
    def form_valid(self, form):
        model = form.save(commit = False)
        model.user = self.request.user
        model.completed = True
        model.save()
        return super().form_valid(form)
    def get_success_url(self, **kwargs) -> str:
        if 'next' in self.request.GET.keys():
            url = self.request.GET['next']
        else:
            url = '/'
        return url

        

site_auth/templates/profile/userprofile.html
{% extends '../account/base.html' %}
{% block extra_head%}
<script>
var status = '{{completed}}'
$(document).ready(function(){
    $('#changedata_form').hide()
    $("#editdata").click(function(){
        $("#data").hide();
        $('#changedata_form').show()
    });
    if (status != 'True'){
        $("#data").hide();
        $('#changedata_form').show()
    }
});
</script>
<style>
  h1{
    text-align: center;
  }
ul li{
  margin: 2%;
  font-size: 20px;
  }

</style>
{% endblock%}
{% block head_title %}
{{title_name}}
{% endblock %}
{% block content %}
<div style="padding-top: 10%; padding-bottom: 10%;">
  <div class="card bg-light" style="padding: 3%; max-width: 800px; margin: auto;" >
      <article  class="center" style="max-width: 800px; ">
        <a type="button" class="btn btn-outline-primary" href ='{{back_url}}'><i class="fa fa-home"></i> กลับ</a> 
<h1>ข้อมูลส่วนตัว</h1>

<p> </p>
<div id = 'data' > 
<ul>
  <h3>ข้อมูลทั่วไป</h3>
    <li>คำนำหน้า : {{data.gender}}</li>
    <li>ชื่อ-นามสกุล : {{data.name}} {{data.surname}}</li>
    <li>ชื่อ-นามสกุล (ภาษาอังกฤษ) : {{data.eng_name}} {{data.eng_surname}}</li>
    <li>ชื่อเล่น : {{data.nickname}}</li>
    <li>รหัสนักศึกษา : {{data.student_id}}</li>
    <li>วันเดือนปีเกิด : {{data.birth_date}}</li>
    <li>ศาสนา : {{data.religion}}</li>
    <h3>ข้อมูลติดต่อ</h3>
    <li>ที่อยู่ : {{data.address}}</li>
    <li>หมายเลขโทรศัพท์ : {{data.self_telephone_num}}</li>
    <li>Line id : {{data.line_id}}</li>
    <li>Facebook : {{data.facebook}}</li>
    <li>instagram : {{data.instagram}}</li>
    <h3>ประวัติการแพ้</h3>
    <li>อาหารที่แพ้ : {{data.allergic_foods}}</li>
    <li>ยาที่แพ้ : {{data.allergic_meds}}</li>
    <li>โรคประจำตัว : {{data.congenital_disease}}</li>
    

</ul>
<button  class="btn btn-warning btn-block" id ='editdata'>แก้ไขข้อมูล</button>
</div>
<div id = 'changedata_form'>
<form method="post" action = ''>
    {% csrf_token %}
    <h3>ข้อมูลทั่วไป</h3>
    <div class="form-group input-group">
        <span class="input-group-text" style="background-color: transparent;border: none;"> 
          <label for="id_name" style="margin: auto; ">คำนำหน้า :</label> </span>
                  {{ form.gender.errors }}
                  {{ form.gender}}
      </div>

    <div class="form-group input-group">
        <span class="input-group-text" style="background-color: transparent;border: none;"> 
          <label for="id_name" style="margin: auto; ">ชื่อ :</label> </span>
                  {{ form.name.errors }}
                  {{ form.name }}
      </div>
  
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_surname" style="margin: auto; ">นามสกุล :</label> </span>
            {{ form.surname.errors }}
              {{ form.surname }}
      </div>
      <div class="form-group input-group">
        <span class="input-group-text" style="background-color: transparent;border: none;"> 
          <label for="id_eng_name" style="margin: auto; ">ชื่อ (ภาษาอังกฤษ) :</label> </span>
                  {{ form.eng_name.errors }}
                  {{ form.eng_name }}
      </div>
  
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_eng_surname" style="margin: auto; ">นามสกุล (ภาษาอังกฤษ) :</label> </span>
            {{ form.eng_surname.errors }}
              {{ form.eng_surname }}
      </div>
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_surname" style="margin: auto; ">ชื่อเล่น :</label> </span>
            {{ form.nickname.errors }}
            {{ form.nickname }}
      </div>
  
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_surname" style="margin: auto; ">รหัสนักศึกษา :</label> </span>
              
              {{ form.student_id }}
      </div>
      <p>{{ form.student_id.errors }}</p>
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_surname" style="margin: auto; ">วันเดือนปีเกิด :</label> </span>
              {{ form.birth_date.errors }}
              {{ form.birth_date }}
      </div>
  
      <div class="form-group input-group">
        <span class="input-group-text" style="background-color: transparent;border: none;"> 
          <label for="id_surname" style="margin: auto; ">ศาสนา :</label> </span>
            {{ form.religion.errors }}
            {{ form.religion }}
      </div> 
      <h3>ข้อมูลติดต่อ</h3>
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_surname" style="margin: auto; ">ที่อยู่ (ที่สามารถรับของได้) :</label> </span>
              {{ form.address.errors }}
              {{ form.address }}
      </div>
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_self_telephone_num" style="margin: auto; ">เบอร์โทรศัพท์ :</label> </span>
              {{ form.self_telephone_num.errors }}
              {{ form.self_telephone_num }}
      </div>
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_surname" style="margin: auto; ">Line id :</label> </span>
              {{ form.line_id.errors }}
              {{ form.line_id }}
      </div>
  
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_surname" style="margin: auto; ">Facebook :</label> </span>
              {{ form.facebook.errors }}
              {{ form.facebook }}
      </div>
  
      <div class="form-group input-group">
          <span class="input-group-text" style="background-color: transparent;border: none;"> 
            <label for="id_surname" style="margin: auto; ">instagram :</label> </span>
              {{ form.instagram.errors }}
              {{ form.instagram }}
      </div> 

      <h3>ประวัติการแพ้ (ถ้าไม่มีใส่  -  )</h3>
      <div class="form-group input-group">
        <span class="input-group-text" style="background-color: transparent;border: none;"> 
          <label for="id_surname" style="margin: auto; ">อาหารที่แพ้ :</label> </span>
            {{ form.allergic_foods.errors }}
            {{ form.allergic_foods }}
      </div> 

      <div class="form-group input-group">
        <span class="input-group-text" style="background-color: transparent;border: none;"> 
          <label for="id_surname" style="margin: auto; ">ยาที่แพ้ :</label> </span>
            {{ form.allergic_meds.errors }}
            {{ form.allergic_meds }}
      </div> 

      <div class="form-group input-group">
        <span class="input-group-text" style="background-color: transparent;border: none;"> 
          <label for="id_surname" style="margin: auto; ">โรคประจำตัว :</label> </span>
            {{ form.congenital_disease.errors }}
            {{ form.congenital_disease }}
      </div> 
      {% if message %}<p style="color: crimson; font-weight: 1000px;">{{message}}</p> {%endif%}
      <button class="btn btn-success btn-block" type="submit" >บันทึกข้อมูล</button>
</form>
</div>
</article>
</div>
</div>
{% endblock %}